export const FRAME_TYPES = {
  TELEMETRY: "TELEMETRY",
  COMMAND_ECHO: "COMMAND_ECHO",
  LOG_ENTRY: "LOG_ENTRY",
  UNKNOWN: "UNKNOWN",
} as const;

export type FrameType = (typeof FRAME_TYPES)[keyof typeof FRAME_TYPES];

export const TELEMETRY_CONSTANTS = {
  CSV_FIELD_COUNT: 35,
  MAX_HISTORY_SIZE: 1000,
  DATA_RATE_TARGET: 10,
  TELEMETRY_INTERVAL: 100,
  LOG_INTERVAL: 5000,
  MAX_BUFFER_SIZE: 5000,
} as const;

export const FLIGHT_STATES = {
  0: "BOOT",
  1: "TEST_MODE",
  2: "LAUNCH_PAD",
  3: "ASCENT",
  4: "ROCKET_DEPLOY",
  5: "DESCENT",
  6: "SECONDARY_DEPLOY",
  7: "FINAL_DESCENT",
  8: "IMPACT",
} as const;

export const getFlightStateName = (state: number): string =>
  FLIGHT_STATES[state as keyof typeof FLIGHT_STATES] || `UNKNOWN(${state})`;

export const XBEE_CONSTANTS = {
  DEFAULT_BAUD_RATE: 9600,
  CONNECTION_TIMEOUT: 5000,
  COMMAND_TIMEOUT: 3000,
  MAX_COMMAND_LENGTH: 50,
  RETRY_ATTEMPTS: 3,
} as const;

export const CLUSTER_IDS = {
  TELEMETRY: 0x0001,
  LOG: 0x0002,
  CMD_RESPONSE: 0x0003,
} as const;

export type ClusterID = (typeof CLUSTER_IDS)[keyof typeof CLUSTER_IDS];

export const GS_COMMANDS = {
  START_TELEMETRY: "START_TX",
  STATUS: "STATUS",
  STOP_TELEMETRY: "STOP_TX",
  CALIBRATE_SENSORS: "CAL_SENSORS",
  RESET_SYSTEM: "RESET",
  EMERGENCY: "EMERGENCY",
  PARACHUTE_DEPLOY: "PARACHUTE_DEPLOY",
  START: "START",
  SHUTDOWN: "SHUTDOWN",
  CLEAR_MISSION: "CLEAR_MISSION",
  SD_CLEAN: "SD_CLEAN",
  SD_INFO: "SD_INFO",
  SD_LIST: "SD_LIST",
  XBEE_RESET: "XBEE_RESET",
  SET_MISSION_START: "SET_MISSION_START",
  GET_TIME: "GET_TIME",
  SET_TIME: "SET_TIME:",
  RTC_STATUS: "RTC_STATUS",
  MCU_STATUS: "MCU_STATUS",
  COMM_STATUS: "COMM_STATUS",
  ARM_RW: "ARM_RW",
  DISARM_RW: "DISARM_RW",
  STOP_RW: "STOP_RW",
  RW_STATUS: "RW_STATUS",
  SET_RW_SPEED: "SET_RW_SPEED:",
  SET_PID_GAINS: "SET_PID:",
} as const;

export const MISSION_CONSTANTS = {
  TEAM_ID: "046",
  SEA_LEVEL_PRESSURE: 1013.25,
  LAUNCH_DETECTION_ALTITUDE: 20.0,
  IMPACT_DETECTION_ALTITUDE: 5.0,
  PARACHUTE_DEPLOY_ALTITUDE: 1000.0,
  SECONDARY_DEPLOY_ALTITUDE: 500.0,
  MAX_ALTITUDE: 1000.0,
  GROUND_LEVEL_ALTITUDE: 100.0,
} as const;

export type FlightState = keyof typeof FLIGHT_STATES;
export type GroundStationCommand =
  (typeof GS_COMMANDS)[keyof typeof GS_COMMANDS];
